#!/usr/bin/env perl
use strict;
use warnings;
use FindBin;
use lib "$FindBin::Bin/../extlib/lib/perl5";
use lib "$FindBin::Bin/../lib";

use Cath::Tiny::App;

Cath::Tiny::App->new_with_cmd->execute();
